# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'numo-narray'
gem 'matplotlib'
gem 'red-datasets'
gem 'test-unit'
gem 'irb'
gem 'pry-byebug'
gem 'rake'
